name: Run Playwright Tests in Docker
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Cache node modules for faster builds
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3
    - name: Build Docker image
      run: docker build -t preetiVijay/playwright-test .
    # - name: Upload Docker image to Docker hub
    #   run: docker push preetiVijay/playwright-test
    - name: Run Docker container with playwright tests
      run: docker run --name playwright-container preetiVijay/playwright-test
    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report
    - name: Print docker container logs (on failure)
      if: failure()
      run: docker logs playwright-container
    - name: Clean up Docker container
      if: always()
      run: docker rm -f playwright-container || true
